name: Recordatorios de tareas

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  recordatorios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install firebase
      - run: node recordatorios.js
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT: ${{ secrets.TG_CHAT }}

          
